const configuredBase = import.meta.env?.BASE_URL ?? "./";
const assetBase = typeof document === "undefined"
  ? configuredBase
  : new URL(configuredBase, document.baseURI).href;

export const SCENES = {
  classroomPreview: `${assetBase}assets/classroom-preview.jpg`,
  classroom: `${assetBase}assets/classroom-rain.jpg`,
  corridor: `${assetBase}assets/old-corridor-rain.jpg`,
  records: `${assetBase}assets/records-room-rain.jpg`,
};

export const FACTS = {
  loop: {
    id: "loop",
    category: "记录",
    title: "循环中的 6 月 16 日",
    description: "午夜之后，所有人都会回到当天 07:10。只有凛完整保留记忆。",
  },
  roster: {
    id: "roster",
    category: "记录",
    title: "值日表被修改",
    description: "去年 6 月 16 日的值日表由神谷悠真事后重写，夏见遥并非独自进入旧楼。",
  },
  witness: {
    id: "witness",
    category: "记录",
    title: "目击者",
    description: "去年六月十六日，全班都被要求在笔录上签字，声称没有看见夏见遥进入旧楼。七个人都签了。",
  },
  eighthSeat: {
    id: "eighthSeat",
    category: "记录",
    title: "第八个座位",
    description: "去年只有一名学生拒绝签字，坚持自己看见了真相。从那以后，全班都“想不起”她。教室因此多出第八张、谁也不认领的桌子。",
  },
};

export const STORY = [
  { id: "wake", scene: "classroom", time: "07:10", speaker: "", text: "铃声离得很近。近得像是从桌子里面响起来的。", sfx: "bell" },
  { id: "yuma-1", scene: "classroom", time: "07:10", speaker: "神谷悠真", text: "醒了？" },
  { id: "rin-1", scene: "classroom", time: "07:10", speaker: "白石凛", text: "……这里是？" },
  { id: "yuma-2", scene: "classroom", time: "07:10", speaker: "神谷悠真", text: "二年 B 班。栖川学园。六月十六日，早上七点十分。" },
  {
    id: "first-choice",
    scene: "classroom",
    time: "07:12",
    speaker: "",
    text: "七名陌生学生看着你。讲台上没有老师，教室里却摆着八张桌子。",
    choices: [
      { label: "“你们是谁？”", key: "tone", value: "cautious", response: "先确认彼此的身份。" },
      { label: "“门为什么锁着？”", key: "tone", value: "direct", response: "先找出离开这里的方法。" },
      { label: "“我为什么会在这里？”", key: "tone", value: "vulnerable", response: "先确认自己是否还记得来处。" },
    ],
  },
  { id: "names", scene: "classroom", time: "07:18", speaker: "神谷悠真", text: "藤泽葵。久世透。黑田陆。水野纱月。御影司。相原澪。还有我。你呢？" },
  { id: "name", scene: "classroom", time: "07:19", speaker: "白石凛", text: "白石凛。" },
  { id: "tsukasa", scene: "classroom", time: "07:20", speaker: "御影司", text: "我们七个都是这所学校的学生。没有人见过你。" },
  { id: "door", scene: "classroom", time: "08:06", speaker: "神谷悠真", text: "门没有上锁。它只是打不开。窗户也一样。" },
  {
    id: "route-choice",
    scene: "classroom",
    time: "08:10",
    speaker: "",
    text: "悠真让所有人分头确认出口。你准备先调查哪里？",
    choices: [
      { label: "检查主教学楼", key: "firstRoute", value: "main", response: "所有时钟都停在 16:16。", responseSpeaker: "" },
      { label: "前往校门", key: "firstRoute", value: "gate", response: "扔进白雾的书包从身后落下。", responseSpeaker: "" },
      { label: "调查广播室", key: "firstRoute", value: "radio", response: "话筒旁摆着八份泛黄的广播稿。", responseSpeaker: "" },
    ],
  },
  { id: "first-reunion", scene: "classroom", time: "11:00", speaker: "", text: "十一点，分散在校园里的八个人重新回到二年 B 班。每组都带回一个无法解释的答案。" },
  { id: "photo", scene: "classroom", time: "11:00", speaker: "久世透", text: "照片里只有七张桌子。" },
  { id: "rin-photo", scene: "classroom", time: "11:00", speaker: "白石凛", text: "这里明明有八张。" },
  { id: "broadcast", scene: "classroom", time: "16:16", speaker: "广播中的女声", text: "请各位同学留在教室。不要接近旧教学楼。", sfx: "static" },
  { id: "umbrella", scene: "classroom", time: "16:16", speaker: "", text: "窗外，一把红伞在雨中停住。你确信刚才那里没有人。", effect: "pulse" },
  { id: "memory", scene: "classroom", time: "18:16", speaker: "未知女声", text: "你们看见了。你们明明都看见了。", effect: "memory", sfx: "memory" },
  { id: "rollcall", scene: "classroom", time: "18:16", speaker: "广播中的女声", text: "白石凛。", sfx: "static" },
  { id: "rin-question", scene: "classroom", time: "18:16", speaker: "白石凛", text: "你认识我？" },
  { id: "answer", scene: "classroom", time: "18:16", speaker: "广播中的女声", text: "不。是他们认识你。" },
  { id: "midnight", scene: "classroom", time: "24:00", speaker: "广播中的女声", text: "本日最后一项失物招领：一把红色雨伞，以及一名没有被任何人完整记住的学生。", effect: "midnight", sfx: "bell" },
  { id: "reset", scene: "classroom", time: "07:10", speaker: "神谷悠真", text: "醒了？这里是二年 B 班。栖川学园。", loop: 2, sfx: "bell" },
  { id: "rin-knows", scene: "classroom", time: "07:10", speaker: "白石凛", text: "我知道。", loop: 2 },
  { id: "loop-line", scene: "classroom", time: "07:10", speaker: "白石凛", text: "这是第二次六月十六日。", loop: 2, fact: "loop" },

  { id: "chapter-one", scene: "classroom", time: "07:11", speaker: "", text: "第一章　缺席者", loop: 2, chapter: "第一章　缺席者", effect: "chapter" },
  { id: "yuma-denial", scene: "classroom", time: "07:11", speaker: "神谷悠真", text: "……你刚才说，第二次？" },
  { id: "rin-proof", scene: "classroom", time: "07:12", speaker: "白石凛", text: "相原澪的抽屉里有一把系着红绳的黄铜钥匙。三分钟后，粉笔会在我的名字上折断。" },
  { id: "chalk", scene: "classroom", time: "07:15", speaker: "", text: "喀。粉笔断成两截。没有人再说话。", sfx: "impact" },
  { id: "aoi-loop", scene: "classroom", time: "07:15", speaker: "藤泽葵", text: "这种事……提前商量也做得到。" },
  { id: "yuma-plan", scene: "classroom", time: "07:16", speaker: "神谷悠真", text: "十一点，我们会在这里重新集合。你说那时久世会拿出一张少了桌子的照片。" },
  { id: "rin-plan", scene: "classroom", time: "07:16", speaker: "白石凛", text: "对。广播会在 16:16 响起。午夜之后，你又会问我同一句话。" },
  { id: "yuma-deja", scene: "classroom", time: "07:17", speaker: "神谷悠真", text: "……粉笔折断以前，我发现自己一直在等那声脆响。" },
  {
    id: "yuma-control",
    scene: "classroom",
    time: "07:18",
    speaker: "神谷悠真",
    decisionKey: "tone",
    variants: {
      cautious: "你记得每个细节。如果今天真的重复过，我们不能照原来的顺序行动。白石，你跟我来。",
      direct: "既然你一醒来就在找出口，现在就和我一起找打破这一天的方法。白石，你跟我来。",
      vulnerable: "如果你也不知道自己为什么会在这里，一个人调查只会更危险。白石，你跟我来。",
    },
  },
  {
    id: "rin-route-memory",
    scene: "classroom",
    time: "07:19",
    speaker: "白石凛",
    decisionKey: "firstRoute",
    variants: {
      main: "上一轮，主教学楼的每一只钟都停在 16:16。",
      gate: "上一轮，扔进校门白雾的书包从我们身后落了下来。",
      radio: "上一轮，停用的广播室里摆着八份写有今天日期的稿件。",
    },
  },

  { id: "records-enter", scene: "records", time: "10:30", speaker: "", text: "教职员资料室比记忆里更窄。雨水沿窗框渗进来，空气里全是纸张受潮的味道。", loop: 2 },
  { id: "records-key", scene: "records", time: "10:31", speaker: "神谷悠真", text: "去年六月的档案在最里面。你想找什么？" },
  {
    id: "records-choice",
    scene: "records",
    time: "10:32",
    speaker: "",
    text: "柜门上没有标签。你只能先查一类记录。",
    choices: [
      { label: "二年 B 班点名册", key: "recordFocus", value: "attendance", response: "黑色胶带的边缘露出一个名字：夏见遥。", responseSpeaker: "" },
      { label: "去年六月值日表", key: "recordFocus", value: "roster", response: "6 月 16 日只写着一个名字：夏见遥。", responseSpeaker: "" },
      { label: "旧教学楼出入记录", key: "recordFocus", value: "access", response: "被撕走的页面留下铅笔压痕：夏见遥，18:10。", responseSpeaker: "" },
    ],
  },
  { id: "records-converge", scene: "records", time: "10:40", speaker: "", text: "十分钟后，三份记录摊在同一张桌上，彼此拼出了同一个缺口。" },
  { id: "haruka-name", scene: "records", time: "10:40", speaker: "白石凛", text: "夏见遥。去年坠楼的学生。" },
  { id: "yuma-cold", scene: "records", time: "10:40", speaker: "神谷悠真", text: "校方认定是意外。他们把这张值日表当成她独自进入旧楼的依据。" },
  { id: "rin-ink", scene: "records", time: "10:42", speaker: "白石凛", text: "其他日期都是黑墨水。只有 6 月 16 日是蓝黑色。" },
  { id: "supply", scene: "records", time: "10:43", speaker: "", text: "档案盒侧面贴着领用记录：蓝黑签字笔，本学年四月更换。" },
  {
    id: "ink-confrontation",
    scene: "records",
    time: "10:44",
    speaker: "",
    text: "这张值日表不可能在去年写成。",
    choices: [
      { label: "“是你重写的。”", key: "confrontation", value: "accuse", response: "你直接指出他的谎言。", responseSpeaker: "" },
      { label: "“你在保护谁？”", key: "confrontation", value: "protect", response: "你先问这句谎言保护了谁。", responseSpeaker: "" },
      { label: "把领用记录放在他面前", key: "confrontation", value: "evidence", response: "你让证据替自己开口。", responseSpeaker: "" },
    ],
  },
  {
    id: "yuma-deflect",
    scene: "records",
    time: "10:45",
    speaker: "神谷悠真",
    decisionKey: "confrontation",
    variants: {
      accuse: "你只凭墨水就指认我？学校每年都会誊写旧档。",
      protect: "有些记录被改，是为了让更多人不被牵连。你还不知道当时的情况。",
      evidence: "领用日期只能证明这是一份誊本，不能证明誊写的人是我。",
    },
  },
  { id: "pressure", scene: "records", time: "10:46", speaker: "", text: "悠真把值日表放回桌面，纸下却浮出另一行被压过的字迹。" },
  { id: "pressure-name", scene: "records", time: "10:46", speaker: "白石凛", text: "神谷悠真。原来的名字是你。" },
  { id: "old-note", scene: "records", time: "10:49", speaker: "", text: "隔壁的纪律档案里还有一张旧检讨。考试资料泄露事件，署名先写了悠真，随后被划掉，换成夏见遥。" },
  { id: "yuma-stop", scene: "records", time: "10:49", speaker: "神谷悠真", text: "别念了。那件事和她的死没有关系。" },
  { id: "rin-relation", scene: "records", time: "10:50", speaker: "白石凛", text: "她替你承担过一次。你又让她在值日表上独自出现。" },
  { id: "yuma-leave", scene: "records", time: "10:51", speaker: "神谷悠真", text: "……到此为止。" },
  { id: "yuma-takes-roster", scene: "records", time: "10:51", speaker: "", text: "悠真抽走那张值日表，折起来塞进口袋，独自离开资料室。" },

  { id: "corridor-enter", scene: "corridor", time: "16:16", speaker: "", text: "旧教学楼的门没有锁。悠真攥着值日表站在连廊尽头，像是被某段看不见的值日铃声叫来的。", loop: 2, sfx: "static" },
  { id: "broadcast-duty", scene: "corridor", time: "16:16", speaker: "广播中的女声", text: "今日值日生，请留在旧教学楼。", sfx: "static" },
  { id: "yuma-fear", scene: "corridor", time: "16:17", speaker: "神谷悠真", text: "去年它没有播过这句话。至少……我不记得。" },
  { id: "tooru-follows", scene: "corridor", time: "16:17", speaker: "", text: "更远处的门影里，久世透举着相机。他没有靠近，也没有离开。" },
  { id: "memory-coffee", scene: "corridor", time: "16:18", speaker: "夏见遥的声音", text: "班长，你总是在收拾别人留下的东西。偶尔也让别人替你一次吧。", effect: "memory", sfx: "memory" },
  { id: "yuma-memory", scene: "corridor", time: "16:18", speaker: "神谷悠真", text: "那天她塞给我一罐热咖啡。明明被记过的人是她，她反而在安慰我。" },
  { id: "rail-shift", scene: "corridor", time: "16:19", speaker: "", text: "连廊护栏发出一声脆响。悠真下意识后退，值日表从他手里滑向积水。", effect: "pulse", sfx: "impact" },
  {
    id: "rescue-choice",
    scene: "corridor",
    time: "16:19",
    speaker: "",
    text: "一瞬间，你只能先抓住一样。",
    choices: [
      { label: "抓住悠真的手", key: "rescue", value: "yuma", response: "你抓住悠真，值日表被雨水浸透。", responseSpeaker: "" },
      { label: "抢救值日表", key: "rescue", value: "roster", response: "你护住证据。久世从门后冲出，勉强拉住悠真。", responseSpeaker: "" },
    ],
  },
  {
    id: "rescue-result",
    scene: "corridor",
    time: "16:20",
    speaker: "神谷悠真",
    decisionKey: "rescue",
    variants: {
      yuma: "为什么？那张表才是你要的证据。",
      roster: "你刚才先拿了那张表。去年……我也先看向了不该看的东西。",
    },
  },
  {
    id: "rin-answer-rescue",
    scene: "corridor",
    time: "16:20",
    speaker: "白石凛",
    decisionKey: "rescue",
    variants: {
      yuma: "证据可以再找。人不行。",
      roster: "我刚才也先看向了证据。和你去年一样。",
    },
  },
  { id: "yuma-confess-one", scene: "corridor", time: "16:21", speaker: "神谷悠真", text: "值日表是我改的。事故之后，我把自己的名字擦掉，只留下遥。" },
  { id: "yuma-confess-two", scene: "corridor", time: "16:21", speaker: "神谷悠真", text: "我告诉自己，这是为了保护还活着的人。死去的人已经不会再失去什么。" },
  { id: "rin-dead", scene: "corridor", time: "16:22", speaker: "白石凛", text: "死去的人也会被谎言伤害。只是她没办法替自己说出来。" },
  { id: "yuma-name", scene: "corridor", time: "16:23", speaker: "神谷悠真", text: "……夏见遥不是独自进入旧楼的。我也在这里。" },
  { id: "roster-fact", scene: "corridor", time: "16:23", speaker: "", text: "悠真第一次没有把那句话称作意外。" },
  { id: "coffee-memory", scene: "corridor", time: "16:25", speaker: "神谷悠真", text: "那罐咖啡其实很难喝。她自己也喝了一口，然后笑了很久。" },
  { id: "human-haruka", scene: "corridor", time: "16:25", speaker: "白石凛", text: "这是今天第一次，有人说起活着的夏见遥。", fact: "roster", sfx: "fact" },
  { id: "final-broadcast", scene: "corridor", time: "18:16", speaker: "夏见遥的声音", text: "这次，请不要先决定我是什么样的人。", effect: "memory", sfx: "static", ending: true },

  { id: "chapter-two", scene: "classroom", time: "07:10", speaker: "", text: "第二章　目击者", loop: 3, chapter: "第二章　目击者", effect: "chapter" },
  { id: "ch2-open", scene: "classroom", time: "07:10", speaker: "", text: "第三轮循环。午夜把一切重置回早上七点十分。凛带走了两张事实卡，和悠真一句连他自己都已忘掉的坦白。", loop: 3, sfx: "bell" },
  { id: "ch2-yuma-1", scene: "classroom", time: "07:10", speaker: "神谷悠真", text: "醒了？这里是二年 B 班。栖川学园。", loop: 3 },
  { id: "ch2-rin-1", scene: "classroom", time: "07:10", speaker: "白石凛", text: "……我知道。", loop: 3 },
  { id: "ch2-yuma-deja", scene: "classroom", time: "07:11", speaker: "神谷悠真", text: "奇怪。你说“知道”的样子，我好像在哪儿见过。", loop: 3 },
  { id: "ch2-kuze-see", scene: "classroom", time: "07:20", speaker: "", text: "凛的目光越过悠真，落在最后一排。久世透举着相机，对着空荡的教室按下快门。", loop: 3 },
  { id: "ch2-rin-kuze", scene: "classroom", time: "07:20", speaker: "白石凛", text: "久世。你每天都在拍。拍给谁看？", loop: 3 },
  { id: "ch2-kuze-1", scene: "classroom", time: "07:20", speaker: "久世透", text: "拍下来，就不用记住了。", loop: 3 },

  { id: "ch2-corridor-enter", scene: "corridor", time: "10:00", speaker: "", text: "走廊尽头的窗外仍在落雨。久世跟了上来，相机垂在胸前。", loop: 3 },
  { id: "ch2-corridor-photo", scene: "corridor", time: "10:00", speaker: "白石凛", text: "合照里只有七张桌子。可你按快门时，明明对着八张。", loop: 3 },
  { id: "ch2-kuze-2", scene: "corridor", time: "10:00", speaker: "久世透", text: "相机不会拍错。是它替我们决定——哪一张不该出现。", loop: 3 },
  { id: "ch2-rin-ask-photo", scene: "corridor", time: "10:01", speaker: "白石凛", text: "把去年的照片给我看。", loop: 3 },
  { id: "ch2-kuze-3", scene: "corridor", time: "10:01", speaker: "久世透", text: "……你确定要看？看过的人，都开始做同一个梦。", loop: 3 },

  { id: "ch2-darkroom-enter", scene: "records", time: "10:30", speaker: "", text: "暗房。红灯下，一张旧照在显影液里慢慢浮起。", loop: 3 },
  { id: "ch2-kuze-4", scene: "records", time: "10:30", speaker: "久世透", text: "那天我在对面楼顶试长焦。我没想拍到那个。", loop: 3 },
  { id: "ch2-photo-figures", scene: "records", time: "10:31", speaker: "", text: "照片边缘，旧楼连廊的护栏旁站着两个人影。一个是夏见遥，另一个撑着红伞。", loop: 3, effect: "pulse" },
  { id: "ch2-rin-umbrella", scene: "records", time: "10:31", speaker: "白石凛", text: "撑伞的是谁？", loop: 3 },
  { id: "ch2-kuze-5", scene: "records", time: "10:32", speaker: "久世透", text: "冲洗出来那天，我谁都没告诉。我把它压在了最底下。", loop: 3 },
  { id: "ch2-rin-realize", scene: "records", time: "11:00", speaker: "白石凛", text: "所以广播说“你们都看见了”——不是指那一瞬间，是指事后。", loop: 3 },
  { id: "ch2-kuze-6", scene: "records", time: "11:00", speaker: "久世透", text: "全班都被叫去做过笔录。我们都签了字，说那天没看见遥上旧楼。", loop: 3 },
  { id: "ch2-rin-accuse", scene: "records", time: "11:01", speaker: "白石凛", text: "你们看见了，却签字说没看见。", loop: 3 },
  { id: "ch2-kuze-7", scene: "records", time: "11:01", speaker: "久世透", text: "老师说，这样对活着的人最好。", loop: 3 },
  { id: "ch2-haruka-memory", scene: "records", time: "11:02", speaker: "夏见遥的声音", text: "你们看见了。你们明明都看见了。", loop: 3, effect: "memory", sfx: "memory" },
  { id: "ch2-witness-fact", scene: "records", time: "11:03", speaker: "", text: "笔录上，七个名字整齐排列。没有一个人写下自己看见了什么。", loop: 3, fact: "witness", sfx: "fact" },

  { id: "ch2-corridor2-enter", scene: "corridor", time: "16:16", speaker: "", text: "旧教学楼的连廊。雨丝斜斜地飘进来。", loop: 3 },
  { id: "ch2-broadcast-duty", scene: "corridor", time: "16:16", speaker: "广播中的女声", text: "今日值日生，请留在旧教学楼。", loop: 3, sfx: "static" },
  { id: "ch2-rin-deduce", scene: "corridor", time: "16:16", speaker: "白石凛", text: "撑红伞的人，比遥晚一步上来，也比她先一步下去。", loop: 3 },
  { id: "ch2-umbrella", scene: "corridor", time: "16:17", speaker: "", text: "连廊尽头，一把红伞靠在护栏边。没有人撑着它，伞下的地面却没有被雨打湿。", loop: 3, effect: "pulse" },
  { id: "ch2-rin-umbrella2", scene: "corridor", time: "16:17", speaker: "白石凛", text: "这把伞从来不属于遥。是有人替她撑过一次，又把它留在了这里。", loop: 3 },
  { id: "ch2-haruka-memory2", scene: "corridor", time: "16:18", speaker: "夏见遥的声音", text: "下雨了，你怎么不打伞。……算了，这把给你。我跑两步就到。", loop: 3, effect: "memory", sfx: "memory" },
  { id: "ch2-rin-recognize", scene: "corridor", time: "16:18", speaker: "白石凛", text: "我认得这句话。", loop: 3 },
  { id: "ch2-rollcall-intro", scene: "corridor", time: "18:16", speaker: "", text: "广播第三次点名，很慢，像怕念错。", loop: 3, sfx: "static" },
  { id: "ch2-rollcall", scene: "corridor", time: "18:16", speaker: "广播中的女声", text: "白石凛。", loop: 3, sfx: "static" },
  { id: "ch2-rin-q", scene: "corridor", time: "18:16", speaker: "白石凛", text: "……你到底认不认识我。", loop: 3 },
  { id: "ch2-broadcast-2", scene: "corridor", time: "18:17", speaker: "广播中的女声", text: "去年这一天，有一个人在笔录上写了“我看见了”。只有一个人。", loop: 3, sfx: "static" },
  { id: "ch2-rin-q2", scene: "corridor", time: "18:17", speaker: "白石凛", text: "那个人后来怎么样了？", loop: 3 },
  { id: "ch2-broadcast-3", scene: "corridor", time: "18:18", speaker: "广播中的女声", text: "从那天起，没有人再记得她坐在哪一张桌子。", loop: 3, sfx: "static" },
  { id: "ch2-eighthseat-fact", scene: "corridor", time: "18:18", speaker: "", text: "教室里那张多出来的桌子，从此谁也不认领。", loop: 3, fact: "eighthSeat", sfx: "fact" },

  { id: "ch2-midnight", scene: "classroom", time: "24:00", speaker: "广播中的女声", text: "本日最后一项失物招领——一把红色雨伞，一名坠楼的学生，以及，一个坚持记得她的人。", loop: 3, effect: "midnight", sfx: "bell" },
  { id: "ch2-reset-narr", scene: "classroom", time: "24:00", speaker: "", text: "循环重置了。但这一次，凛没有立刻睁开眼。", loop: 3 },
  { id: "ch2-rin-mono", scene: "classroom", time: "24:00", speaker: "白石凛", text: "第八个座位是我的。我不是被困在这一天的人——我是被这一天，一直留在原地的人。", loop: 3 },
  { id: "ch2-loop4-wake", scene: "classroom", time: "07:10", speaker: "神谷悠真", text: "醒了？这里是——", loop: 4, sfx: "bell" },
  { id: "ch2-loop4-pause", scene: "classroom", time: "07:10", speaker: "", text: "他停住，没有把那句话念完。", loop: 4 },
  { id: "ch2-ending", scene: "classroom", time: "07:10", speaker: "神谷悠真", text: "……白石。你的桌子，为什么我今天第一次看清了它在哪儿。", loop: 4, effect: "memory", ending: true },
];

export function resolveText(line, decisions) {
  if (!line.variants || !line.decisionKey) return line.text;
  return line.variants[decisions[line.decisionKey]] ?? line.text ?? "";
}
