const configuredBase = import.meta.env?.BASE_URL ?? "./";
const assetBase = typeof document === "undefined"
  ? configuredBase
  : new URL(configuredBase, document.baseURI).href;

export const SCENES = {
  classroomPreview: `${assetBase}assets/classroom-preview.jpg`,
  classroom: `${assetBase}assets/classroom-rain.jpg`,
  corridor: `${assetBase}assets/old-corridor-rain.jpg`,
  records: `${assetBase}assets/records-room-rain.jpg`,
};

export const FACTS = {
  loop: {
    id: "loop",
    category: "记录",
    title: "循环中的 6 月 16 日",
    description: "午夜之后，所有人都会回到当天 07:10。只有凛完整保留记忆。",
  },
  roster: {
    id: "roster",
    category: "记录",
    title: "值日表被修改",
    description: "去年 6 月 16 日的值日表由神谷悠真事后重写，夏见遥并非独自进入旧楼。",
  },
  aoiVoice: {
    id: "aoiVoice",
    category: "证言",
    title: "遥发过求助语音",
    description: "藤泽葵在 16:16 收到遥的求助语音，却因前一晚争吵没有赶去旧楼。",
  },
  tooruPhoto: {
    id: "tooruPhoto",
    category: "证言",
    title: "透在现场旁观",
    description: "久世透拍到护栏断裂与众人在场，但交出的照片被裁切过。",
  },
  rikuRelease: {
    id: "rikuRelease",
    category: "证言",
    title: "陆抓住后又松手",
    description: "黑田陆与遥争夺手机时拉住了她，随后因恐惧和疼痛松开手。",
  },
  satsukiPrivacy: {
    id: "satsukiPrivacy",
    category: "关系",
    title: "医疗隐私被交给校方",
    description: "水野纱月把遥的就诊记录交给校方，使事故被解释成精神状态异常。",
  },
  tsukasaMaterials: {
    id: "tsukasaMaterials",
    category: "记录",
    title: "安全材料被销毁",
    description: "御影司曾把旧楼安全调查交给校方，校方承诺维修后销毁了材料。",
  },
  mioMessage: {
    id: "mioMessage",
    category: "证言",
    title: "澪伪造最后留言",
    description: "相原澪用遥的账号发出“不要怪任何人”的信息，试图尽快结束调查。",
  },
  rinIdentity: {
    id: "rinIdentity",
    category: "关系",
    title: "不存在的转学生",
    description: "白石凛没有学籍和身体，是七人对夏见遥的矛盾记忆在循环中形成的人格。",
  },
  responsibilityOrder: {
    id: "responsibilityOrder",
    category: "记录",
    title: "18:16 的责任顺序",
    description: "护栏断裂是直接原因，拉扯、迟疑、延误报警和事后篡改共同构成关键责任。",
  },
};

export const CHAPTERS = [
  { id: "prologue", title: "序章　雨没有停", index: 0 },
  { id: "chapter-one", title: "第一章　缺席者" },
  { id: "chapter-two", title: "第二章　七种证词" },
  { id: "chapter-three", title: "第三章　第八张桌子" },
  { id: "chapter-four", title: "第四章　18:16" },
  { id: "finale", title: "终章　6/17" },
];

export const CHAPTER_ONE_DEFAULT_DECISIONS = {
  tone: "cautious",
  firstRoute: "main",
};

export const CHAPTER_DEFAULT_DECISIONS = {
  "chapter-one": CHAPTER_ONE_DEFAULT_DECISIONS,
  "chapter-two": {
    ...CHAPTER_ONE_DEFAULT_DECISIONS,
    recordFocus: "roster",
    confrontation: "evidence",
    rescue: "yuma",
  },
  "chapter-three": {
    ...CHAPTER_ONE_DEFAULT_DECISIONS,
    recordFocus: "roster",
    confrontation: "evidence",
    rescue: "yuma",
    testimonyFocus: "aoi",
  },
  "chapter-four": {
    ...CHAPTER_ONE_DEFAULT_DECISIONS,
    recordFocus: "roster",
    confrontation: "evidence",
    rescue: "yuma",
    testimonyFocus: "aoi",
    identityChoice: "public",
  },
  finale: {
    ...CHAPTER_ONE_DEFAULT_DECISIONS,
    recordFocus: "roster",
    confrontation: "evidence",
    rescue: "yuma",
    testimonyFocus: "aoi",
    identityChoice: "public",
    reconstruction: "order",
  },
};

export const STORY = [
  { id: "wake", scene: "classroom", time: "07:10", speaker: "", text: "铃声离得很近。近得像是从桌子里面响起来的。", sfx: "bell" },
  { id: "yuma-1", scene: "classroom", time: "07:10", speaker: "神谷悠真", text: "醒了？" },
  { id: "rin-1", scene: "classroom", time: "07:10", speaker: "白石凛", text: "……这里是？" },
  { id: "yuma-2", scene: "classroom", time: "07:10", speaker: "神谷悠真", text: "二年 B 班。栖川学园。六月十六日，早上七点十分。" },
  {
    id: "first-choice",
    scene: "classroom",
    time: "07:12",
    speaker: "",
    text: "七名陌生学生看着你。讲台上没有老师，教室里却摆着八张桌子。",
    choices: [
      { label: "“你们是谁？”", key: "tone", value: "cautious", response: "先确认彼此的身份。" },
      { label: "“门为什么锁着？”", key: "tone", value: "direct", response: "先找出离开这里的方法。" },
      { label: "“我为什么会在这里？”", key: "tone", value: "vulnerable", response: "先确认自己是否还记得来处。" },
    ],
  },
  { id: "names", scene: "classroom", time: "07:18", speaker: "神谷悠真", text: "藤泽葵。久世透。黑田陆。水野纱月。御影司。相原澪。还有我。你呢？" },
  { id: "name", scene: "classroom", time: "07:19", speaker: "白石凛", text: "白石凛。" },
  { id: "tsukasa", scene: "classroom", time: "07:20", speaker: "御影司", text: "我们七个都是这所学校的学生。没有人见过你。" },
  { id: "door", scene: "classroom", time: "08:06", speaker: "神谷悠真", text: "门没有上锁。它只是打不开。窗户也一样。" },
  {
    id: "route-choice",
    scene: "classroom",
    time: "08:10",
    speaker: "",
    text: "悠真让所有人分头确认出口。你准备先调查哪里？",
    choices: [
      { label: "检查主教学楼", key: "firstRoute", value: "main", response: "所有时钟都停在 16:16。", responseSpeaker: "" },
      { label: "前往校门", key: "firstRoute", value: "gate", response: "扔进白雾的书包从身后落下。", responseSpeaker: "" },
      { label: "调查广播室", key: "firstRoute", value: "radio", response: "话筒旁摆着八份泛黄的广播稿。", responseSpeaker: "" },
    ],
  },
  { id: "first-reunion", scene: "classroom", time: "11:00", speaker: "", text: "十一点，分散在校园里的八个人重新回到二年 B 班。每组都带回一个无法解释的答案。" },
  { id: "photo", scene: "classroom", time: "11:00", speaker: "久世透", text: "照片里只有七张桌子。" },
  { id: "rin-photo", scene: "classroom", time: "11:00", speaker: "白石凛", text: "这里明明有八张。" },
  { id: "broadcast", scene: "classroom", time: "16:16", speaker: "广播中的女声", text: "请各位同学留在教室。不要接近旧教学楼。", sfx: "static" },
  { id: "umbrella", scene: "classroom", time: "16:16", speaker: "", text: "窗外，一把红伞在雨中停住。你确信刚才那里没有人。", effect: "pulse" },
  { id: "memory", scene: "classroom", time: "18:16", speaker: "未知女声", text: "你们看见了。你们明明都看见了。", effect: "memory", sfx: "memory" },
  { id: "rollcall", scene: "classroom", time: "18:16", speaker: "广播中的女声", text: "白石凛。", sfx: "static" },
  { id: "rin-question", scene: "classroom", time: "18:16", speaker: "白石凛", text: "你认识我？" },
  { id: "answer", scene: "classroom", time: "18:16", speaker: "广播中的女声", text: "不。是他们认识你。" },
  { id: "midnight", scene: "classroom", time: "24:00", speaker: "广播中的女声", text: "本日最后一项失物招领：一把红色雨伞，以及一名没有被任何人完整记住的学生。", effect: "midnight", sfx: "bell" },
  { id: "reset", scene: "classroom", time: "07:10", speaker: "神谷悠真", text: "醒了？这里是二年 B 班。栖川学园。", loop: 2, sfx: "bell" },
  { id: "rin-knows", scene: "classroom", time: "07:10", speaker: "白石凛", text: "我知道。", loop: 2 },
  { id: "loop-line", scene: "classroom", time: "07:10", speaker: "白石凛", text: "这是第二次六月十六日。", loop: 2, fact: "loop" },

  { id: "chapter-one", scene: "classroom", time: "07:11", speaker: "", text: "第一章　缺席者", loop: 2, chapter: "第一章　缺席者", effect: "chapter" },
  { id: "yuma-denial", scene: "classroom", time: "07:11", speaker: "神谷悠真", text: "……你刚才说，第二次？" },
  { id: "rin-proof", scene: "classroom", time: "07:12", speaker: "白石凛", text: "相原澪的抽屉里有一把系着红绳的黄铜钥匙。三分钟后，粉笔会在我的名字上折断。" },
  { id: "chalk", scene: "classroom", time: "07:15", speaker: "", text: "喀。粉笔断成两截。没有人再说话。", sfx: "impact" },
  { id: "aoi-loop", scene: "classroom", time: "07:15", speaker: "藤泽葵", text: "这种事……提前商量也做得到。" },
  { id: "yuma-plan", scene: "classroom", time: "07:16", speaker: "神谷悠真", text: "十一点，我们会在这里重新集合。你说那时久世会拿出一张少了桌子的照片。" },
  { id: "rin-plan", scene: "classroom", time: "07:16", speaker: "白石凛", text: "对。广播会在 16:16 响起。午夜之后，你又会问我同一句话。" },
  { id: "yuma-deja", scene: "classroom", time: "07:17", speaker: "神谷悠真", text: "……粉笔折断以前，我发现自己一直在等那声脆响。" },
  {
    id: "yuma-control",
    scene: "classroom",
    time: "07:18",
    speaker: "神谷悠真",
    decisionKey: "tone",
    variants: {
      cautious: "你记得每个细节。如果今天真的重复过，我们不能照原来的顺序行动。白石，你跟我来。",
      direct: "既然你一醒来就在找出口，现在就和我一起找打破这一天的方法。白石，你跟我来。",
      vulnerable: "如果你也不知道自己为什么会在这里，一个人调查只会更危险。白石，你跟我来。",
    },
  },
  {
    id: "rin-route-memory",
    scene: "classroom",
    time: "07:19",
    speaker: "白石凛",
    decisionKey: "firstRoute",
    variants: {
      main: "上一轮，主教学楼的每一只钟都停在 16:16。",
      gate: "上一轮，扔进校门白雾的书包从我们身后落了下来。",
      radio: "上一轮，停用的广播室里摆着八份写有今天日期的稿件。",
    },
  },

  { id: "records-enter", scene: "records", time: "10:30", speaker: "", text: "教职员资料室比记忆里更窄。雨水沿窗框渗进来，空气里全是纸张受潮的味道。", loop: 2 },
  { id: "records-key", scene: "records", time: "10:31", speaker: "神谷悠真", text: "去年六月的档案在最里面。你想找什么？" },
  {
    id: "records-choice",
    scene: "records",
    time: "10:32",
    speaker: "",
    text: "柜门上没有标签。你只能先查一类记录。",
    choices: [
      { label: "二年 B 班点名册", key: "recordFocus", value: "attendance", response: "黑色胶带的边缘露出一个名字：夏见遥。", responseSpeaker: "" },
      { label: "去年六月值日表", key: "recordFocus", value: "roster", response: "6 月 16 日只写着一个名字：夏见遥。", responseSpeaker: "" },
      { label: "旧教学楼出入记录", key: "recordFocus", value: "access", response: "被撕走的页面留下铅笔压痕：夏见遥，18:10。", responseSpeaker: "" },
    ],
  },
  { id: "records-converge", scene: "records", time: "10:40", speaker: "", text: "十分钟后，三份记录摊在同一张桌上，彼此拼出了同一个缺口。" },
  { id: "haruka-name", scene: "records", time: "10:40", speaker: "白石凛", text: "夏见遥。去年坠楼的学生。" },
  { id: "yuma-cold", scene: "records", time: "10:40", speaker: "神谷悠真", text: "校方认定是意外。他们把这张值日表当成她独自进入旧楼的依据。" },
  { id: "rin-ink", scene: "records", time: "10:42", speaker: "白石凛", text: "其他日期都是黑墨水。只有 6 月 16 日是蓝黑色。" },
  { id: "supply", scene: "records", time: "10:43", speaker: "", text: "档案盒侧面贴着领用记录：蓝黑签字笔，本学年四月更换。" },
  {
    id: "ink-confrontation",
    scene: "records",
    time: "10:44",
    speaker: "",
    text: "这张值日表不可能在去年写成。",
    choices: [
      { label: "“是你重写的。”", key: "confrontation", value: "accuse", response: "你直接指出他的谎言。", responseSpeaker: "" },
      { label: "“你在保护谁？”", key: "confrontation", value: "protect", response: "你先问这句谎言保护了谁。", responseSpeaker: "" },
      { label: "把领用记录放在他面前", key: "confrontation", value: "evidence", response: "你让证据替自己开口。", responseSpeaker: "" },
    ],
  },
  {
    id: "yuma-deflect",
    scene: "records",
    time: "10:45",
    speaker: "神谷悠真",
    decisionKey: "confrontation",
    variants: {
      accuse: "你只凭墨水就指认我？学校每年都会誊写旧档。",
      protect: "有些记录被改，是为了让更多人不被牵连。你还不知道当时的情况。",
      evidence: "领用日期只能证明这是一份誊本，不能证明誊写的人是我。",
    },
  },
  { id: "pressure", scene: "records", time: "10:46", speaker: "", text: "悠真把值日表放回桌面，纸下却浮出另一行被压过的字迹。" },
  { id: "pressure-name", scene: "records", time: "10:46", speaker: "白石凛", text: "神谷悠真。原来的名字是你。" },
  { id: "old-note", scene: "records", time: "10:49", speaker: "", text: "隔壁的纪律档案里还有一张旧检讨。考试资料泄露事件，署名先写了悠真，随后被划掉，换成夏见遥。" },
  { id: "yuma-stop", scene: "records", time: "10:49", speaker: "神谷悠真", text: "别念了。那件事和她的死没有关系。" },
  { id: "rin-relation", scene: "records", time: "10:50", speaker: "白石凛", text: "她替你承担过一次。你又让她在值日表上独自出现。" },
  { id: "yuma-leave", scene: "records", time: "10:51", speaker: "神谷悠真", text: "……到此为止。" },
  { id: "yuma-takes-roster", scene: "records", time: "10:51", speaker: "", text: "悠真抽走那张值日表，折起来塞进口袋，独自离开资料室。" },

  { id: "corridor-enter", scene: "corridor", time: "16:16", speaker: "", text: "旧教学楼的门没有锁。悠真攥着值日表站在连廊尽头，像是被某段看不见的值日铃声叫来的。", loop: 2, sfx: "static" },
  { id: "broadcast-duty", scene: "corridor", time: "16:16", speaker: "广播中的女声", text: "今日值日生，请留在旧教学楼。", sfx: "static" },
  { id: "yuma-fear", scene: "corridor", time: "16:17", speaker: "神谷悠真", text: "去年它没有播过这句话。至少……我不记得。" },
  { id: "tooru-follows", scene: "corridor", time: "16:17", speaker: "", text: "更远处的门影里，久世透举着相机。他没有靠近，也没有离开。" },
  { id: "memory-coffee", scene: "corridor", time: "16:18", speaker: "夏见遥的声音", text: "班长，你总是在收拾别人留下的东西。偶尔也让别人替你一次吧。", effect: "memory", sfx: "memory" },
  { id: "yuma-memory", scene: "corridor", time: "16:18", speaker: "神谷悠真", text: "那天她塞给我一罐热咖啡。明明被记过的人是她，她反而在安慰我。" },
  { id: "rail-shift", scene: "corridor", time: "16:19", speaker: "", text: "连廊护栏发出一声脆响。悠真下意识后退，值日表从他手里滑向积水。", effect: "pulse", sfx: "impact" },
  {
    id: "rescue-choice",
    scene: "corridor",
    time: "16:19",
    speaker: "",
    text: "一瞬间，你只能先抓住一样。",
    choices: [
      { label: "抓住悠真的手", key: "rescue", value: "yuma", response: "你抓住悠真，值日表被雨水浸透。", responseSpeaker: "" },
      { label: "抢救值日表", key: "rescue", value: "roster", response: "你护住证据。久世从门后冲出，勉强拉住悠真。", responseSpeaker: "" },
    ],
  },
  {
    id: "rescue-result",
    scene: "corridor",
    time: "16:20",
    speaker: "神谷悠真",
    decisionKey: "rescue",
    variants: {
      yuma: "为什么？那张表才是你要的证据。",
      roster: "你刚才先拿了那张表。去年……我也先看向了不该看的东西。",
    },
  },
  {
    id: "rin-answer-rescue",
    scene: "corridor",
    time: "16:20",
    speaker: "白石凛",
    decisionKey: "rescue",
    variants: {
      yuma: "证据可以再找。人不行。",
      roster: "我刚才也先看向了证据。和你去年一样。",
    },
  },
  { id: "yuma-confess-one", scene: "corridor", time: "16:21", speaker: "神谷悠真", text: "值日表是我改的。事故之后，我把自己的名字擦掉，只留下遥。" },
  { id: "yuma-confess-two", scene: "corridor", time: "16:21", speaker: "神谷悠真", text: "我告诉自己，这是为了保护还活着的人。死去的人已经不会再失去什么。" },
  { id: "rin-dead", scene: "corridor", time: "16:22", speaker: "白石凛", text: "死去的人也会被谎言伤害。只是她没办法替自己说出来。" },
  { id: "yuma-name", scene: "corridor", time: "16:23", speaker: "神谷悠真", text: "……夏见遥不是独自进入旧楼的。我也在这里。" },
  { id: "roster-fact", scene: "corridor", time: "16:23", speaker: "", text: "悠真第一次没有把那句话称作意外。" },
  { id: "coffee-memory", scene: "corridor", time: "16:25", speaker: "神谷悠真", text: "那罐咖啡其实很难喝。她自己也喝了一口，然后笑了很久。" },
  { id: "human-haruka", scene: "corridor", time: "16:25", speaker: "白石凛", text: "这是今天第一次，有人说起活着的夏见遥。", fact: "roster", sfx: "fact" },
  { id: "final-broadcast", scene: "corridor", time: "18:16", speaker: "夏见遥的声音", text: "这次，请不要先决定我是什么样的人。", effect: "memory", sfx: "static" },

  { id: "chapter-two", scene: "classroom", time: "07:10", speaker: "", text: "第二章　七种证词", loop: 3, chapter: "第二章　七种证词", effect: "chapter", sfx: "bell" },
  { id: "third-loop", scene: "classroom", time: "07:10", speaker: "白石凛", text: "第三次醒来时，悠真没有再问“醒了”。他只是把值日表推到桌面中央。" },
  { id: "shared-memory-start", scene: "classroom", time: "07:11", speaker: "神谷悠真", text: "我记得资料室，也记得旧连廊。也许承认一件事之后，循环就不能再替我忘记。" },
  {
    id: "testimony-focus",
    scene: "classroom",
    time: "07:12",
    speaker: "",
    text: "七个人各自坐在不同的阴影里。你决定先让谁开口？",
    choices: [
      { label: "先问藤泽葵", key: "testimonyFocus", value: "aoi", response: "你把旧音乐播放器放到葵面前。", responseSpeaker: "" },
      { label: "先问久世透", key: "testimonyFocus", value: "tooru", response: "你把裁切照片推到透的相机旁。", responseSpeaker: "" },
      { label: "先问黑田陆", key: "testimonyFocus", value: "riku", response: "你让陆看见护栏上的握痕方向。", responseSpeaker: "" },
      { label: "先问水野纱月", key: "testimonyFocus", value: "satsuki", response: "你展开保健室就诊表的复印件。", responseSpeaker: "" },
      { label: "先问御影司", key: "testimonyFocus", value: "tsukasa", response: "你报出打印机缓存里的会议编号。", responseSpeaker: "" },
      { label: "先问相原澪", key: "testimonyFocus", value: "mio", response: "你把未寄出的生日卡放到澪的桌上。", responseSpeaker: "" },
      { label: "让七个人按时间顺序说", key: "testimonyFocus", value: "order", response: "你在黑板写下 16:16、18:10、18:16 三个时间。", responseSpeaker: "" },
    ],
  },
  {
    id: "focus-response",
    scene: "classroom",
    time: "07:13",
    speaker: "白石凛",
    decisionKey: "testimonyFocus",
    variants: {
      aoi: "葵，你最早听见遥的求救。先从你开始。",
      tooru: "透，你的相机比你先承认了现场。先从你开始。",
      riku: "陆，所有人都害怕你像凶手，但这不是让你沉默的理由。",
      satsuki: "纱月，善意如果被别人拿去伤害她，也必须被说出来。",
      tsukasa: "司，你比任何人都清楚旧楼不是安全的。",
      mio: "澪，你不是旁观者。你只是把自己的姓藏起来了。",
      order: "我们不先找凶手。我们先还原每个人在时间线上做过什么。",
    },
  },
  { id: "aoi-route-start", scene: "classroom", time: "10:30", speaker: "", text: "葵的手机在没有信号的校园里亮起。云端缓存里，一段被删除的语音停在 16:16。" },
  { id: "aoi-voice", scene: "classroom", time: "10:31", speaker: "夏见遥的声音", text: "葵，如果你还在生气，至少别让他们一个人去旧楼。拜托。", effect: "memory", sfx: "memory" },
  { id: "aoi-confess", scene: "classroom", time: "10:32", speaker: "藤泽葵", text: "我听见了。可前一天晚上我刚骂她总是装好人。我想让她也尝一次没人回头的感觉。" },
  { id: "aoi-memory", scene: "classroom", time: "10:33", speaker: "藤泽葵", text: "小时候下雨，她会把两个人的书包都顶在头上，自己淋得最湿。那时候我以为她永远不会离开我。", fact: "aoiVoice", sfx: "fact" },
  { id: "tooru-route-start", scene: "corridor", time: "13:00", speaker: "", text: "久世透把相机放在旧连廊地面。连拍编号从 0416 跳到 0423，中间七张照片不存在。" },
  { id: "tooru-photo", scene: "corridor", time: "13:01", speaker: "久世透", text: "我没删底片。我只是把能看见人的部分裁掉了。这样照片就只剩事故，不剩我。" },
  { id: "tooru-memory", scene: "corridor", time: "13:02", speaker: "久世透", text: "她给我的摄影展评语写得很长。最后一句是：你拍到的人，比你想象中更希望被看见。", fact: "tooruPhoto", sfx: "fact" },
  { id: "riku-route-start", scene: "corridor", time: "16:16", speaker: "", text: "护栏上的旧握痕在雨水里浮出方向。不是有人把遥推开，而是有人曾经用力抓住她。" },
  { id: "riku-confess", scene: "corridor", time: "16:17", speaker: "黑田陆", text: "我只想抢她手机。名单在里面，里面有我做过的事。我抓住她了，可她喊疼，我就松了。" },
  { id: "riku-memory", scene: "corridor", time: "16:18", speaker: "黑田陆", text: "她退回我的道歉信，说道歉不是给自己减刑用的。那封信我到现在还背得出来。", fact: "rikuRelease", sfx: "fact" },
  { id: "satsuki-route-start", scene: "records", time: "16:30", speaker: "", text: "保健室就诊表与校方事故报告并排放着。两份文件用了同一句话：情绪长期不稳定。" },
  { id: "satsuki-confess", scene: "records", time: "16:31", speaker: "水野纱月", text: "他们说只是确认她是否需要帮助。我母亲在学校医务室工作。我以为照做就能保护所有人。" },
  { id: "satsuki-memory", scene: "records", time: "16:32", speaker: "水野纱月", text: "遥给我写过一张助眠清单。第一条是“不要把别人的痛苦当成自己的任务”。我没有做到。", fact: "satsukiPrivacy", sfx: "fact" },
  { id: "tsukasa-route-start", scene: "records", time: "16:40", speaker: "", text: "打印机缓存吐出一行会议编号。旧楼维修提案曾被提交，又在告别仪式前被撤回。" },
  { id: "tsukasa-confess", scene: "records", time: "16:41", speaker: "御影司", text: "我相信内部解决。相信只要材料交给正确的人，事情就会变好。结果他们销毁了材料，也利用了我的沉默。" },
  { id: "tsukasa-memory", scene: "records", time: "16:42", speaker: "御影司", text: "遥在调查笔记边上画过歪掉的护栏，还写：副会长，不要只相信盖章的东西。", fact: "tsukasaMaterials", sfx: "fact" },
  { id: "mio-route-start", scene: "classroom", time: "16:50", speaker: "", text: "澪的旧姓从生日卡背面渗出。夏见澪。她和遥拥有同一张家庭照片，只是照片被剪成了两半。" },
  { id: "mio-confess", scene: "classroom", time: "16:51", speaker: "相原澪", text: "我拿走她的手机，发了那条“不要怪任何人”。母亲求我让事情结束。我也想让姐姐变成一个没有缺点的死者。" },
  { id: "mio-memory", scene: "classroom", time: "16:52", speaker: "相原澪", text: "她没有寄出的生日卡里写：澪，如果我总像姐姐一样命令你，对不起。我其实也不知道怎么当姐姐。", fact: "mioMessage", sfx: "fact" },
  { id: "seven-testimonies-close", scene: "classroom", time: "24:00", speaker: "广播中的女声", text: "七种证词已接收。谎言不再只属于一个人。", effect: "midnight", sfx: "bell" },

  { id: "chapter-three", scene: "classroom", time: "07:10", speaker: "", text: "第三章　第八张桌子", loop: 4, chapter: "第三章　第八张桌子", effect: "chapter", sfx: "bell" },
  { id: "identity-records", scene: "records", time: "10:30", speaker: "", text: "点名册、转学记录、保健室登记、图书借阅卡，所有系统里都没有白石凛。" },
  { id: "mirror", scene: "classroom", time: "11:00", speaker: "", text: "窗玻璃映出你的脸。葵看见小时候的遥，透看见摄影展那天的遥，澪看见离家前一晚的姐姐。" },
  { id: "ask-identity", scene: "classroom", time: "11:01", speaker: "白石凛", text: "我让你们想起谁？" },
  { id: "identity-answer", scene: "classroom", time: "11:02", speaker: "御影司", text: "不是同一个人。我们每个人记得的遥都不完整，于是循环把那些碎片拼成了你。" },
  {
    id: "identity-choice",
    scene: "classroom",
    time: "11:03",
    speaker: "",
    text: "如果真相继续推进，凛也许会随循环一起结束。你决定怎么告诉他们？",
    choices: [
      { label: "公开自己的身份", key: "identityChoice", value: "public", response: "你把不存在的学籍号写在黑板上。", responseSpeaker: "" },
      { label: "暂时隐瞒恐惧", key: "identityChoice", value: "hidden", response: "你把手从点名册上移开，没有立刻说出消失的可能。", responseSpeaker: "" },
    ],
  },
  {
    id: "identity-result",
    scene: "classroom",
    time: "11:04",
    speaker: "白石凛",
    decisionKey: "identityChoice",
    variants: {
      public: "如果我是你们的记忆，那也由我来确认：遥不是任何一个人方便保存的样子。",
      hidden: "我还不能确定自己会变成什么。但至少现在，我能继续把你们带到 18:16。",
    },
  },
  { id: "umbrella-touch", scene: "corridor", time: "16:16", speaker: "", text: "凛触碰红伞。她看见的不是遥的眼睛，而是七个人同时看向坠落处的瞬间。", effect: "memory", fact: "rinIdentity", sfx: "fact" },

  { id: "chapter-four", scene: "corridor", time: "16:16", speaker: "", text: "第四章　18:16", loop: 5, chapter: "第四章　18:16", effect: "chapter", sfx: "static" },
  { id: "rebuild-start", scene: "corridor", time: "16:16", speaker: "广播中的女声", text: "请按真实顺序重演。不要用一个名字代替所有选择。" },
  {
    id: "reconstruction-choice",
    scene: "corridor",
    time: "16:17",
    speaker: "",
    text: "旧连廊在雨中恢复去年形状。你先指出什么？",
    choices: [
      { label: "按责任顺序还原", key: "reconstruction", value: "order", response: "你先指向松脱护栏，再让每个人站回自己的位置。", responseSpeaker: "" },
      { label: "把责任归给陆", key: "reconstruction", value: "blameRiku", response: "你指向陆，所有阴影都朝他压过去。", responseSpeaker: "" },
      { label: "把责任归给司", key: "reconstruction", value: "blameTsukasa", response: "你指向司，会议编号在雨中反复闪烁。", responseSpeaker: "" },
    ],
  },
  {
    id: "reconstruction-result",
    scene: "corridor",
    time: "16:18",
    speaker: "白石凛",
    decisionKey: "reconstruction",
    variants: {
      order: "护栏先断，陆先抓住又松手。悠真和司迟疑，透没有现身，葵没有赶来，纱月的记录和澪的信息让谎言留到第二年。",
      blameRiku: "陆的手最接近坠落，但如果只留下他的名字，其他人的沉默会重新变成无罪。",
      blameTsukasa: "司交出的材料打开了校方的遮蔽，但如果只留下他的名字，连廊上的每一次迟疑都会消失。",
    },
  },
  { id: "reconstruction-corrective", scene: "corridor", time: "16:19", speaker: "夏见遥的声音", text: "我不需要一个替大家承担的凶手。我需要你们把自己做过的事说完整。", effect: "memory" },
  { id: "responsibility-fact", scene: "corridor", time: "18:16", speaker: "", text: "连廊终于不再重复坠落声。雨水沿护栏滴下，像一条被接回去的时间线。", fact: "responsibilityOrder", sfx: "fact" },

  { id: "finale", scene: "classroom", time: "07:10", speaker: "", text: "终章　6/17", loop: 6, chapter: "终章　6/17", effect: "chapter", sfx: "bell" },
  { id: "final-morning", scene: "classroom", time: "07:10", speaker: "", text: "第六次早晨，没有人再假装只是做了同一个噩梦。八张桌子围成一圈，中央放着所有事实卡。" },
  {
    id: "focus-echo",
    scene: "classroom",
    time: "07:12",
    speaker: "",
    decisionKey: "testimonyFocus",
    variants: {
      aoi: "葵最先站起来，给遥的号码重新留言：这次我会去。",
      tooru: "透把未裁切原图导出到两张存储卡，一张交给凛，一张留给警方。",
      riku: "陆把道歉信摊开，第一次没有用坏脾气替自己挡住问题。",
      satsuki: "纱月写下母亲的名字，也写下自己把记录递出去的手。",
      tsukasa: "司把会议编号、打印缓存和旧楼报告按日期排好。",
      mio: "澪把姐姐的生日卡贴回另一半家庭照旁边。",
      order: "七个人按时间顺序复述证词，没有人再插队替别人解释。",
    },
  },
  {
    id: "final-choice",
    scene: "classroom",
    time: "07:16",
    speaker: "",
    text: "雨声第一次变远。校门外出现 6 月 17 日的晨光。你选择怎样结束？",
    choices: [
      { label: "让 6 月 16 日结束", key: "endingPath", value: "true", response: "你把红伞放回第八张桌子。", responseSpeaker: "" },
      { label: "强行从校门离开", key: "endingPath", value: "normal", response: "你走向校门，白雾被现实的光撕开。", responseSpeaker: "" },
      { label: "维持第八名学生的存在", key: "endingPath", value: "eighth", response: "你抓住桌沿，不让第八张桌子消失。", responseSpeaker: "" },
      { label: "只和最先开口的人承担记忆", key: "endingPath", value: "character", response: "你把第一张证词卡留在掌心。", responseSpeaker: "" },
    ],
  },
  {
    id: "ending-title",
    scene: "classroom",
    time: "07:17",
    speaker: "",
    decisionKey: "endingPath",
    variants: {
      true: "真结局：明日",
      normal: "普通结局：无雨",
      eighth: "坏结局：第八名学生",
      character: "角色结局：未寄出的信",
    },
    effect: "memory",
  },
  {
    id: "ending-body",
    scene: "classroom",
    time: "07:18",
    speaker: "",
    decisionKey: "endingPath",
    variants: {
      true: "6 月 17 日 07:10，现实教室里只剩七张桌子。悠真报警，透提交原图，葵恢复语音，司递交旧楼材料，纱月与澪分别联系家属。桌面留下一圈红伞滴下的水痕。",
      normal: "众人回到现实，却说不出夏见遥的名字。旧楼拆除现场发现新的证物，新闻日期在屏幕角落跳回 6 月 16 日。",
      eighth: "合照里终于出现清晰的白石凛。随后，七个人的面孔从照片边缘依次褪去，教室铃声重新响起。",
      character: "循环缩小为一间只属于第一张证词的房间。有人和凛一起记得遥，但其余人离开时带走了沉默。",
    },
    ending: true,
  },
];

export function resolveText(line, decisions) {
  if (!line.variants || !line.decisionKey) return line.text;
  return line.variants[decisions[line.decisionKey]] ?? line.text ?? "";
}
